### ISSUE TITLE
Please Version With Questions from db sqllite (with no json)

### ISSUE THREAD

**Issue by caneto** [AndreiD/surveylib#4]

**Comment by CrandellWS** [comment]
I think this is better as json myself because then it is easier to tie to an already existing database. Though, a working demo would be practical...

http://developer.android.com/training/basics/data-storage/databases.html

It really comes down to how sqlite writes...

> Multiple processes can have the same database open at the same time. Multiple processes can be doing a SELECT at the same time. But only one process can be making changes to the database at any moment in time, however.

see -> http://stackoverflow.com/a/1005218/1815624

Just for perspective see -> http://stackoverflow.com/a/11333633/1815624

**Comment by CrandellWS** [comment]
Here is another library for just the database, it may help...
https://github.com/kvirair/SQLite-Simple-Android 

In a pinch, or someone looking for an easy way to change the question, one could use preferences (but this has many drawbacks)

**Comment by AndreiD** [comment]
Listen people... This is not fitting to be a library
I was thinking that people who use this "library" better just download the files, copy paste them, and easily edit them, because in 99% it would require custom stuff
